// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrEugyMSk-7zWYU8l77fWEzQ7VjnK9kR4',
    appId: '1:971434104484:web:896037de27c135fc6eb831',
    messagingSenderId: '971434104484',
    projectId: 'chat-app-23e3b',
    authDomain: 'chat-app-23e3b.firebaseapp.com',
    storageBucket: 'chat-app-23e3b.appspot.com',
    measurementId: 'G-PLEQRHB5PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU9vJS27bc_atrF3wpmj39C4PICSY9xK0',
    appId: '1:971434104484:android:b6e7a657bdc8b61d6eb831',
    messagingSenderId: '971434104484',
    projectId: 'chat-app-23e3b',
    storageBucket: 'chat-app-23e3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPaLyNatk1nMRzsugXTASt3TBpyYNqRTA',
    appId: '1:971434104484:ios:4f2e92774481f8e46eb831',
    messagingSenderId: '971434104484',
    projectId: 'chat-app-23e3b',
    storageBucket: 'chat-app-23e3b.appspot.com',
    iosBundleId: 'com.example.miniWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPaLyNatk1nMRzsugXTASt3TBpyYNqRTA',
    appId: '1:971434104484:ios:4f2e92774481f8e46eb831',
    messagingSenderId: '971434104484',
    projectId: 'chat-app-23e3b',
    storageBucket: 'chat-app-23e3b.appspot.com',
    iosBundleId: 'com.example.miniWhatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrEugyMSk-7zWYU8l77fWEzQ7VjnK9kR4',
    appId: '1:971434104484:web:fa06289e9851fe5f6eb831',
    messagingSenderId: '971434104484',
    projectId: 'chat-app-23e3b',
    authDomain: 'chat-app-23e3b.firebaseapp.com',
    storageBucket: 'chat-app-23e3b.appspot.com',
    measurementId: 'G-X02SH8V026',
  );
}
